# name: CI Docker Build

# on:
#   push:
#     branches: [cd]  # Trigger on push to cd branch
#   workflow_dispatch:  # Manual trigger for testing

# env:
#   DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
#   DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
#   DOCKERHUB_IMAGE: ${{ secrets.DOCKERHUB_IMAGE }}
#   DOCKERHUB_TAG: ${{ secrets.DOCKERHUB_TAG }}
#   DOCKER_CONTAINER_NAME: ${{ secrets.DOCKER_CONTAINER_NAME }}
#   AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
#   EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
#   EC2_IP_ADDRESS: ${{ secrets.EC2_IP_ADDRESS }}

# jobs:
#   build:
#     name: 🛠️ CI - Build & Push Docker Image
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3

#       - name: Login to Docker Hub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}

#       - name: Build and push Docker image
#         uses: docker/build-push-action@v6
#         with:
#           context: .
#           file: ./Dockerfile
#           push: true
#           tags: ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_IMAGE }}:latest
